#! /bin/zsh

print_usage () {
  echo "usage: ./git-create -s server_name -u user_name -n repo_name"
}

while getopts 's:u:n:' flag; do
	case "${flag}" in
	  s) server=$OPTARG ;;
	  u) user=$OPTARG ;;
	  n) name=$OPTARG ;;
	  *) print_usage
	     exit 1;;
	esac
done

remote="${user}@${server}"

ssh $remote "./git-create-remote -n $name"

git clone $remote":repos/$name.git"
